//! Rules Bundle Module - Load Complete Tax Rules from JSON
//!
//! This module enables loading of complete state tax rules from a JSON bundle
//! generated by the TypeScript export script. This eliminates the need for
//! duplicate Rust implementations of state rules.
//!
//! # Architecture
//!
//! ```text
//! ┌─────────────────────────────┐    ┌──────────────────────┐    ┌─────────────────┐
//! │  TypeScript Rules           │    │  JSON Bundle         │    │  Rust WASM      │
//! │  (shared/autoTaxEngine/)    │ -> │  (export script)     │ -> │  (runtime load) │
//! │  SINGLE SOURCE OF TRUTH     │    │  tax-rules-bundle    │    │                 │
//! └─────────────────────────────┘    └──────────────────────┘    └─────────────────┘
//! ```
//!
//! # Usage
//!
//! 1. Generate JSON bundle: `npx tsx scripts/export-tax-rules.ts`
//! 2. Load bundle via `initialize_rules(json)` at app startup
//! 3. Use `get_rules_for_state(code)` to access rules
//! 4. Falls back to minimal defaults if no bundle loaded

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{RwLock, PoisonError};
use once_cell::sync::Lazy;
use std::fmt;
use crate::types::*;

// ============================================================================
// Error Types for Rules Bundle Operations
// ============================================================================

/// Error type for rules bundle operations
///
/// Provides explicit handling for lock poisoning and other failure modes
/// instead of silently swallowing errors with `.unwrap_or()`.
#[derive(Debug)]
pub enum RulesBundleError {
    /// The RwLock was poisoned by a panicking thread
    LockPoisoned(String),
    /// Rules have not been initialized
    NotInitialized,
    /// Invalid rules data
    InvalidRules(String),
    /// JSON parsing error
    ParseError(String),
}

impl fmt::Display for RulesBundleError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RulesBundleError::LockPoisoned(msg) => write!(f, "Rules bundle lock poisoned: {}", msg),
            RulesBundleError::NotInitialized => write!(f, "Rules bundle not initialized"),
            RulesBundleError::InvalidRules(msg) => write!(f, "Invalid rules: {}", msg),
            RulesBundleError::ParseError(msg) => write!(f, "Parse error: {}", msg),
        }
    }
}

impl std::error::Error for RulesBundleError {}

impl<T> From<PoisonError<T>> for RulesBundleError {
    fn from(e: PoisonError<T>) -> Self {
        RulesBundleError::LockPoisoned(format!("{}", e))
    }
}

// ============================================================================
// Global Rules Store (Thread-Safe)
// ============================================================================

/// Global rules bundle store
static RULES_BUNDLE: Lazy<RwLock<Option<RulesBundleV1>>> = Lazy::new(|| RwLock::new(None));

/// Check if rules have been initialized
///
/// Returns `Ok(true)` if rules are loaded, `Ok(false)` if not initialized,
/// or `Err` if the lock is poisoned.
pub fn rules_initialized() -> Result<bool, RulesBundleError> {
    let guard = RULES_BUNDLE.read()?;
    Ok(guard.is_some())
}

/// Check if rules have been initialized (legacy compatibility)
///
/// DEPRECATED: Use `rules_initialized()` which returns a Result.
pub fn rules_initialized_unchecked() -> bool {
    RULES_BUNDLE.read().map(|r| r.is_some()).unwrap_or(false)
}

/// Initialize rules from JSON bundle
///
/// Returns metadata on success, or an error if parsing fails or lock is poisoned.
pub fn initialize_rules(json: &str) -> Result<RulesBundleMetadata, RulesBundleError> {
    let bundle: RulesBundleV1 = serde_json::from_str(json)
        .map_err(|e| RulesBundleError::ParseError(format!("Failed to parse rules bundle: {}", e)))?;

    // Validate
    bundle.validate()
        .map_err(|e| RulesBundleError::InvalidRules(e))?;

    let metadata = bundle.metadata.clone();

    // Store - propagate poison error explicitly
    let mut store = RULES_BUNDLE.write()?;
    *store = Some(bundle);

    Ok(metadata)
}

/// Initialize rules from JSON bundle (legacy String error compatibility)
pub fn initialize_rules_compat(json: &str) -> Result<RulesBundleMetadata, String> {
    initialize_rules(json).map_err(|e| e.to_string())
}

/// Clear loaded rules
///
/// Returns `Ok(())` on success, or `Err` if the lock is poisoned.
pub fn clear_rules() -> Result<(), RulesBundleError> {
    let mut store = RULES_BUNDLE.write()?;
    *store = None;
    Ok(())
}

/// Clear loaded rules (legacy compatibility, ignores poison)
///
/// DEPRECATED: Use `clear_rules()` which returns a Result.
pub fn clear_rules_unchecked() {
    if let Ok(mut store) = RULES_BUNDLE.write() {
        *store = None;
    }
}

/// Get state rules from loaded bundle
///
/// Returns rules for the given state, or an error if:
/// - Lock is poisoned
/// - Rules not initialized
/// - State not found
pub fn get_loaded_state_rules(state_code: &str) -> Result<TaxRulesConfig, RulesBundleError> {
    let guard = RULES_BUNDLE.read()?;
    let bundle = guard.as_ref().ok_or(RulesBundleError::NotInitialized)?;
    bundle
        .states
        .get(state_code)
        .map(|entry| entry.to_tax_rules_config())
        .ok_or_else(|| RulesBundleError::InvalidRules(format!("Unknown state: {}", state_code)))
}

/// Get state rules from loaded bundle (legacy compatibility)
///
/// DEPRECATED: Use `get_loaded_state_rules()` which returns a Result.
pub fn get_loaded_state_rules_opt(state_code: &str) -> Option<TaxRulesConfig> {
    RULES_BUNDLE.read().ok().and_then(|guard| {
        guard.as_ref().and_then(|bundle| {
            bundle.states.get(state_code).map(|entry| entry.to_tax_rules_config())
        })
    })
}

/// Get metadata from loaded bundle
///
/// Returns metadata if rules are loaded, or an error if:
/// - Lock is poisoned
/// - Rules not initialized
pub fn get_rules_bundle_metadata() -> Result<RulesBundleMetadata, RulesBundleError> {
    let guard = RULES_BUNDLE.read()?;
    let bundle = guard.as_ref().ok_or(RulesBundleError::NotInitialized)?;
    Ok(bundle.metadata.clone())
}

/// Get metadata from loaded bundle (legacy compatibility)
///
/// DEPRECATED: Use `get_rules_bundle_metadata()` which returns a Result.
pub fn get_rules_bundle_metadata_opt() -> Option<RulesBundleMetadata> {
    RULES_BUNDLE.read().ok().and_then(|guard| {
        guard.as_ref().map(|bundle| bundle.metadata.clone())
    })
}

/// Get list of available states from bundle
///
/// Returns list of state codes, or an error if:
/// - Lock is poisoned
/// - Rules not initialized
pub fn get_available_states() -> Result<Vec<String>, RulesBundleError> {
    let guard = RULES_BUNDLE.read()?;
    let bundle = guard.as_ref().ok_or(RulesBundleError::NotInitialized)?;
    Ok(bundle.states.keys().cloned().collect())
}

/// Get list of available states from bundle (legacy compatibility)
///
/// DEPRECATED: Use `get_available_states()` which returns a Result.
pub fn get_available_states_unchecked() -> Vec<String> {
    RULES_BUNDLE.read().ok().map(|guard| {
        guard.as_ref().map(|bundle| {
            bundle.states.keys().cloned().collect()
        }).unwrap_or_default()
    }).unwrap_or_default()
}

// ============================================================================
// JSON Schema Types (Match TypeScript Export)
// ============================================================================

/// Rules Bundle V1 - Complete state tax rules
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RulesBundleV1 {
    pub metadata: RulesBundleMetadata,
    pub states: HashMap<String, StateRuleEntry>,
}

impl RulesBundleV1 {
    pub fn validate(&self) -> Result<(), String> {
        if self.states.is_empty() {
            return Err("Rules bundle contains no states".to_string());
        }
        Ok(())
    }
}

/// Bundle metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RulesBundleMetadata {
    pub bundle_id: String,
    pub bundle_version: String,
    pub generated_at: String,
    pub state_count: u32,
    pub source: String,
    pub schema_version: String,
    pub checksum: String,
}

/// State rule entry from JSON
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StateRuleEntry {
    pub state_code: String,
    pub version: u32,
    pub trade_in_policy: TradeInPolicyJson,
    pub rebates: Vec<RebateRuleJson>,
    pub doc_fee_taxable: bool,
    pub fee_tax_rules: Vec<FeeTaxRuleJson>,
    pub tax_on_accessories: bool,
    pub tax_on_negative_equity: bool,
    pub tax_on_service_contracts: bool,
    pub tax_on_gap: bool,
    pub vehicle_tax_scheme: String,
    pub vehicle_uses_local_sales_tax: bool,
    pub lease_rules: LeaseRulesJson,
    pub reciprocity: ReciprocityRulesJson,
    #[serde(default)]
    pub extras: Option<StateExtrasJson>,
}

impl StateRuleEntry {
    /// Convert JSON entry to full TaxRulesConfig
    pub fn to_tax_rules_config(&self) -> TaxRulesConfig {
        TaxRulesConfig {
            state_code: self.state_code.clone(),
            version: self.version,
            trade_in_policy: self.trade_in_policy.to_trade_in_policy(),
            rebates: self.rebates.iter().map(|r| r.to_rebate_rule()).collect(),
            doc_fee_taxable: self.doc_fee_taxable,
            fee_tax_rules: self.fee_tax_rules.iter().map(|r| r.to_fee_tax_rule()).collect(),
            tax_on_accessories: self.tax_on_accessories,
            tax_on_negative_equity: self.tax_on_negative_equity,
            tax_on_service_contracts: self.tax_on_service_contracts,
            tax_on_gap: self.tax_on_gap,
            vehicle_tax_scheme: self.parse_vehicle_tax_scheme(),
            vehicle_uses_local_sales_tax: self.vehicle_uses_local_sales_tax,
            lease_rules: self.lease_rules.to_lease_rules(),
            reciprocity: self.reciprocity.to_reciprocity_rules(),
            extras: self.extras.as_ref().map(|e| e.to_state_extras()),
        }
    }

    fn parse_vehicle_tax_scheme(&self) -> VehicleTaxScheme {
        match self.vehicle_tax_scheme.as_str() {
            "STATE_ONLY" => VehicleTaxScheme::StateOnly,
            "STATE_PLUS_LOCAL" => VehicleTaxScheme::StatePlusLocal,
            "LOCAL_ONLY" => VehicleTaxScheme::LocalOnly,
            "SPECIAL_HUT" => VehicleTaxScheme::SpecialHut,
            "SPECIAL_TAVT" => VehicleTaxScheme::SpecialTavt,
            "DMV_PRIVILEGE_TAX" => VehicleTaxScheme::DmvPrivilegeTax,
            _ => VehicleTaxScheme::StateOnly,
        }
    }
}

// ============================================================================
// JSON Sub-Types
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradeInPolicyJson {
    #[serde(rename = "type")]
    pub policy_type: String,
    pub cap_amount: Option<f64>,
    pub percent: Option<f64>,
    pub notes: Option<String>,
}

impl TradeInPolicyJson {
    pub fn to_trade_in_policy(&self) -> TradeInPolicy {
        match self.policy_type.as_str() {
            "NONE" => TradeInPolicy::None { notes: self.notes.clone() },
            "FULL" => TradeInPolicy::Full { notes: self.notes.clone() },
            "CAPPED" => TradeInPolicy::Capped {
                cap_amount: self.cap_amount.unwrap_or(0.0),
                notes: self.notes.clone(),
            },
            "PERCENT" => TradeInPolicy::Percent {
                percent: self.percent.unwrap_or(0.0),
                notes: self.notes.clone(),
            },
            _ => TradeInPolicy::Full { notes: None },
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RebateRuleJson {
    pub applies_to: String,
    pub taxable: bool,
    pub notes: Option<String>,
}

impl RebateRuleJson {
    pub fn to_rebate_rule(&self) -> RebateRule {
        RebateRule {
            applies_to: match self.applies_to.as_str() {
                "MANUFACTURER" => RebateType::Manufacturer,
                "DEALER" => RebateType::Dealer,
                _ => RebateType::Any,
            },
            taxable: self.taxable,
            notes: self.notes.clone(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeeTaxRuleJson {
    pub code: String,
    pub taxable: bool,
    pub notes: Option<String>,
}

impl FeeTaxRuleJson {
    pub fn to_fee_tax_rule(&self) -> FeeTaxRule {
        FeeTaxRule {
            code: self.code.clone(),
            taxable: self.taxable,
            notes: self.notes.clone(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaseRulesJson {
    pub method: String,
    pub tax_cap_reduction: bool,
    pub rebate_behavior: String,
    pub doc_fee_taxability: String,
    pub trade_in_credit: String,
    pub negative_equity_taxable: bool,
    pub fee_tax_rules: Vec<FeeTaxRuleJson>,
    pub title_fee_rules: Vec<TitleFeeRuleJson>,
    pub tax_fees_upfront: bool,
    pub special_scheme: String,
    pub notes: Option<String>,
}

impl LeaseRulesJson {
    pub fn to_lease_rules(&self) -> LeaseTaxRules {
        LeaseTaxRules {
            method: self.parse_method(),
            tax_cap_reduction: self.tax_cap_reduction,
            rebate_behavior: self.parse_rebate_behavior(),
            doc_fee_taxability: self.parse_doc_fee_taxability(),
            trade_in_credit: self.parse_trade_in_credit(),
            negative_equity_taxable: self.negative_equity_taxable,
            fee_tax_rules: self.fee_tax_rules.iter().map(|r| r.to_fee_tax_rule()).collect(),
            title_fee_rules: self.title_fee_rules.iter().map(|r| r.to_title_fee_rule()).collect(),
            tax_fees_upfront: self.tax_fees_upfront,
            special_scheme: self.parse_special_scheme(),
            notes: self.notes.clone(),
        }
    }

    fn parse_method(&self) -> LeaseMethod {
        match self.method.as_str() {
            "FULL_UPFRONT" => LeaseMethod::FullUpfront,
            "MONTHLY" => LeaseMethod::Monthly,
            "HYBRID" => LeaseMethod::Hybrid,
            "NET_CAP_COST" => LeaseMethod::NetCapCost,
            "REDUCED_BASE" => LeaseMethod::ReducedBase,
            _ => LeaseMethod::Monthly,
        }
    }

    fn parse_rebate_behavior(&self) -> LeaseRebateBehavior {
        match self.rebate_behavior.as_str() {
            "ALWAYS_TAXABLE" => LeaseRebateBehavior::AlwaysTaxable,
            "ALWAYS_NON_TAXABLE" => LeaseRebateBehavior::AlwaysNonTaxable,
            "FOLLOW_RETAIL_RULE" => LeaseRebateBehavior::FollowRetailRule,
            "NON_TAXABLE_IF_AT_SIGNING" => LeaseRebateBehavior::NonTaxableIfAtSigning,
            "NON_TAXABLE_IF_ASSIGNABLE" => LeaseRebateBehavior::NonTaxableIfAssignable,
            _ => LeaseRebateBehavior::FollowRetailRule,
        }
    }

    fn parse_doc_fee_taxability(&self) -> LeaseDocFeeTaxability {
        match self.doc_fee_taxability.as_str() {
            "ALWAYS" => LeaseDocFeeTaxability::Always,
            "FOLLOW_RETAIL_RULE" => LeaseDocFeeTaxability::FollowRetailRule,
            "NEVER" => LeaseDocFeeTaxability::Never,
            "ONLY_UPFRONT" => LeaseDocFeeTaxability::OnlyUpfront,
            _ => LeaseDocFeeTaxability::FollowRetailRule,
        }
    }

    fn parse_trade_in_credit(&self) -> LeaseTradeInCreditMode {
        match self.trade_in_credit.as_str() {
            "NONE" => LeaseTradeInCreditMode::None,
            "FULL" => LeaseTradeInCreditMode::Full,
            "CAP_COST_ONLY" => LeaseTradeInCreditMode::CapCostOnly,
            "APPLIED_TO_PAYMENT" => LeaseTradeInCreditMode::AppliedToPayment,
            "FOLLOW_RETAIL_RULE" => LeaseTradeInCreditMode::FollowRetailRule,
            _ => LeaseTradeInCreditMode::FollowRetailRule,
        }
    }

    fn parse_special_scheme(&self) -> LeaseSpecialScheme {
        match self.special_scheme.as_str() {
            "NONE" => LeaseSpecialScheme::None,
            "NY_MTR" => LeaseSpecialScheme::NyMtr,
            "NJ_LUXURY" => LeaseSpecialScheme::NjLuxury,
            "PA_LEASE_TAX" => LeaseSpecialScheme::PaLeaseTax,
            "IL_CHICAGO_COOK" => LeaseSpecialScheme::IlChicagoCook,
            "TX_LEASE_SPECIAL" => LeaseSpecialScheme::TxLeaseSpecial,
            "VA_USAGE" => LeaseSpecialScheme::VaUsage,
            "MD_UPFRONT_GAIN" => LeaseSpecialScheme::MdUpfrontGain,
            "CO_HOME_RULE_LEASE" => LeaseSpecialScheme::CoHomeRuleLease,
            "GA_TAVT" => LeaseSpecialScheme::GaTavt,
            _ => LeaseSpecialScheme::None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TitleFeeRuleJson {
    pub code: String,
    pub taxable: bool,
    pub included_in_cap_cost: bool,
    pub included_in_upfront: bool,
    pub included_in_monthly: bool,
}

impl TitleFeeRuleJson {
    pub fn to_title_fee_rule(&self) -> TitleFeeRule {
        TitleFeeRule {
            code: self.code.clone(),
            taxable: self.taxable,
            included_in_cap_cost: self.included_in_cap_cost,
            included_in_upfront: self.included_in_upfront,
            included_in_monthly: self.included_in_monthly,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReciprocityRulesJson {
    pub enabled: bool,
    pub scope: String,
    pub home_state_behavior: String,
    pub require_proof_of_tax_paid: bool,
    pub basis: String,
    pub cap_at_this_states_tax: bool,
    pub has_lease_exception: bool,
    pub notes: Option<String>,
}

impl ReciprocityRulesJson {
    pub fn to_reciprocity_rules(&self) -> ReciprocityRules {
        ReciprocityRules {
            enabled: self.enabled,
            scope: self.parse_scope(),
            home_state_behavior: self.parse_behavior(),
            require_proof_of_tax_paid: self.require_proof_of_tax_paid,
            basis: self.parse_basis(),
            cap_at_this_states_tax: self.cap_at_this_states_tax,
            has_lease_exception: self.has_lease_exception,
            overrides: None,
            exempt_states: None,
            non_reciprocal_states: None,
            notes: self.notes.clone(),
        }
    }

    fn parse_scope(&self) -> ReciprocityScope {
        match self.scope.as_str() {
            "NONE" => ReciprocityScope::None,
            "RETAIL_ONLY" => ReciprocityScope::RetailOnly,
            "LEASE_ONLY" => ReciprocityScope::LeaseOnly,
            "BOTH" => ReciprocityScope::Both,
            _ => ReciprocityScope::None,
        }
    }

    fn parse_behavior(&self) -> ReciprocityMode {
        match self.home_state_behavior.as_str() {
            "NONE" => ReciprocityMode::None,
            "CREDIT_UP_TO_STATE_RATE" => ReciprocityMode::CreditUpToStateRate,
            "CREDIT_FULL" => ReciprocityMode::CreditFull,
            "HOME_STATE_ONLY" => ReciprocityMode::HomeStateOnly,
            _ => ReciprocityMode::None,
        }
    }

    fn parse_basis(&self) -> ReciprocityBasis {
        match self.basis.as_str() {
            "TAX_PAID" => ReciprocityBasis::TaxPaid,
            "TAX_DUE_AT_OTHER_STATE_RATE" => ReciprocityBasis::TaxDueAtOtherStateRate,
            _ => ReciprocityBasis::TaxPaid,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StateExtrasJson {
    pub state_automotive_sales_rate: Option<f64>,
    pub state_automotive_lease_rate: Option<f64>,
    pub local_tax_range: Option<LocalTaxRangeJson>,
    pub combined_rate_range: Option<LocalTaxRangeJson>,
    pub doc_fee_cap: Option<f64>,
    pub title_fee: Option<f64>,
    pub notes: Option<String>,
    pub status: Option<String>,
    // Special schemes
    pub ga_tavt: Option<GaTavtJson>,
    pub nc_hut: Option<NcHutJson>,
    pub wv_privilege: Option<WvPrivilegeJson>,
    pub sc_cap: Option<ScCapJson>,
}

impl StateExtrasJson {
    pub fn to_state_extras(&self) -> StateExtras {
        StateExtras {
            state_automotive_sales_rate: self.state_automotive_sales_rate,
            state_automotive_lease_rate: self.state_automotive_lease_rate,
            local_tax_range: self.local_tax_range.as_ref().map(|r| LocalTaxRange { min: r.min, max: r.max }),
            combined_rate_range: self.combined_rate_range.as_ref().map(|r| LocalTaxRange { min: r.min, max: r.max }),
            doc_fee_cap: self.doc_fee_cap.map(|cap| DocFeeCap::Amount(cap)),
            title_fee: self.title_fee,
            notes: self.notes.clone(),
            ga_tavt: self.ga_tavt.as_ref().map(|t| GeorgiaTAVTConfig {
                default_rate: t.default_rate,
                use_assessed_value: t.use_assessed_value,
                use_higher_of_price_or_assessed: false,
                allow_trade_in_credit: t.allow_trade_in_credit,
                trade_in_applies_to: TAVTTradeInApplication::VehicleOnly,
                apply_negative_equity_to_base: false,
                lease_base_mode: TAVTLeaseBaseMode::AgreedValue,
            }),
            nc_hut: self.nc_hut.as_ref().map(|h| NorthCarolinaHUTConfig {
                base_rate: h.base_rate,
                use_highway_use_tax: h.use_highway_use_tax,
                include_trade_in_reduction: true,
                apply_to_net_price_only: true,
                max_reciprocity_age_days: h.max_reciprocity_age_days,
            }),
            wv_privilege: self.wv_privilege.as_ref().map(|w| WestVirginiaPrivilegeConfig {
                base_rate: w.base_rate,
                use_assessed_value: w.use_assessed_value,
                use_higher_of_price_or_assessed: true,
                allow_trade_in_credit: w.allow_trade_in_credit,
                apply_negative_equity_to_base: false,
                vehicle_class_rates: None,
            }),
            sc_cap: self.sc_cap.as_ref().map(|s| SouthCarolinaCapConfig {
                cap_amount: s.cap_amount,
                state_rate: s.state_rate,
                allow_trade_in_credit: true,
                applies_to_leases: true,
            }),
            ..Default::default()
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalTaxRangeJson {
    pub min: f64,
    pub max: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GaTavtJson {
    pub default_rate: f64,
    pub use_assessed_value: bool,
    pub allow_trade_in_credit: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NcHutJson {
    pub base_rate: f64,
    pub use_highway_use_tax: bool,
    pub max_reciprocity_age_days: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WvPrivilegeJson {
    pub base_rate: f64,
    pub use_assessed_value: bool,
    pub allow_trade_in_credit: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScCapJson {
    pub cap_amount: f64,
    pub state_rate: f64,
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_BUNDLE: &str = r#"{
        "metadata": {
            "bundle_id": "test-bundle",
            "bundle_version": "1.0.0",
            "generated_at": "2025-01-01T00:00:00Z",
            "state_count": 1,
            "source": "test",
            "schema_version": "1.0",
            "checksum": "abc123"
        },
        "states": {
            "IN": {
                "state_code": "IN",
                "version": 2,
                "trade_in_policy": { "type": "FULL" },
                "rebates": [
                    { "applies_to": "MANUFACTURER", "taxable": false }
                ],
                "doc_fee_taxable": true,
                "fee_tax_rules": [],
                "tax_on_accessories": true,
                "tax_on_negative_equity": true,
                "tax_on_service_contracts": true,
                "tax_on_gap": true,
                "vehicle_tax_scheme": "STATE_ONLY",
                "vehicle_uses_local_sales_tax": false,
                "lease_rules": {
                    "method": "MONTHLY",
                    "tax_cap_reduction": false,
                    "rebate_behavior": "FOLLOW_RETAIL_RULE",
                    "doc_fee_taxability": "ALWAYS",
                    "trade_in_credit": "FULL",
                    "negative_equity_taxable": true,
                    "fee_tax_rules": [],
                    "title_fee_rules": [],
                    "tax_fees_upfront": true,
                    "special_scheme": "NONE"
                },
                "reciprocity": {
                    "enabled": true,
                    "scope": "BOTH",
                    "home_state_behavior": "CREDIT_UP_TO_STATE_RATE",
                    "require_proof_of_tax_paid": true,
                    "basis": "TAX_PAID",
                    "cap_at_this_states_tax": true,
                    "has_lease_exception": false
                },
                "extras": {
                    "state_automotive_sales_rate": 0.07
                }
            }
        }
    }"#;

    #[test]
    fn test_parse_bundle() {
        let bundle: RulesBundleV1 = serde_json::from_str(SAMPLE_BUNDLE).unwrap();
        assert_eq!(bundle.metadata.state_count, 1);
        assert!(bundle.states.contains_key("IN"));
    }

    #[test]
    fn test_convert_to_config() {
        let bundle: RulesBundleV1 = serde_json::from_str(SAMPLE_BUNDLE).unwrap();
        let entry = bundle.states.get("IN").unwrap();
        let config = entry.to_tax_rules_config();

        assert_eq!(config.state_code, "IN");
        assert_eq!(config.version, 2);
        assert!(matches!(config.trade_in_policy, TradeInPolicy::Full { .. }));
        assert!(matches!(config.vehicle_tax_scheme, VehicleTaxScheme::StateOnly));
        assert!(matches!(config.lease_rules.method, LeaseMethod::Monthly));
    }

    #[test]
    fn test_initialize_and_retrieve() {
        let _ = clear_rules(); // Reset from any prior tests

        let result = initialize_rules(SAMPLE_BUNDLE);
        assert!(result.is_ok());
        assert!(rules_initialized().unwrap_or(false));

        let rules = get_loaded_state_rules("IN");
        assert!(rules.is_ok());
        let rules = rules.unwrap();
        assert_eq!(rules.state_code, "IN");

        assert!(clear_rules().is_ok());
        assert!(!rules_initialized().unwrap_or(true));
    }

    #[test]
    fn test_not_initialized_error() {
        // Clear first to ensure clean state
        let _ = clear_rules();

        // Accessing rules when not initialized should return NotInitialized error
        let result = get_loaded_state_rules("IN");
        assert!(matches!(result, Err(RulesBundleError::NotInitialized)));
    }
}
