CREATE TABLE deals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dealership_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  vehicle_id uuid,
  salesperson_id uuid,
  status text NOT NULL DEFAULT 'lead',
  deal_type text NOT NULL DEFAULT 'finance',
  delivery_method text NOT NULL DEFAULT 'drive_off',
  delivery_destination_state text,
  bill_of_lading text,
  tax_state_code text,
  tax_jurisdiction_code text,
  tax_combined_rate numeric(6,5),
  tax_amount numeric(12,2),
  sale_price numeric(12,2),
  trade_allowance numeric(12,2),
  trade_payoff numeric(12,2),
  cash_down numeric(12,2),
  rebates numeric(12,2),
  amount_financed numeric(12,2),
  apr numeric(5,3),
  term_months integer,
  monthly_payment numeric(10,2),
  residual_value numeric(12,2),
  money_factor numeric(8,6),
  lease_payment numeric(10,2),
  doc_fee numeric(10,2),
  other_fees numeric(10,2),
  total_due numeric(12,2),
  notes text,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now(),
  closed_at timestamp
);
