// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: deals.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDeal = `-- name: CreateDeal :one
INSERT INTO deals (
  dealership_id,
  customer_id,
  vehicle_id,
  salesperson_id,
  status,
  deal_type,
  delivery_method,
  delivery_destination_state,
  bill_of_lading,
  tax_state_code,
  tax_jurisdiction_code,
  tax_combined_rate,
  tax_amount,
  sale_price,
  trade_allowance,
  trade_payoff,
  cash_down,
  rebates,
  amount_financed,
  apr,
  term_months,
  monthly_payment,
  residual_value,
  money_factor,
  lease_payment,
  doc_fee,
  other_fees,
  total_due,
  notes
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
  $21, $22, $23, $24, $25, $26, $27, $28, $29
)
RETURNING id, dealership_id, customer_id, vehicle_id, salesperson_id, status, deal_type, delivery_method, delivery_destination_state, bill_of_lading, tax_state_code, tax_jurisdiction_code, tax_combined_rate, tax_amount, sale_price, trade_allowance, trade_payoff, cash_down, rebates, amount_financed, apr, term_months, monthly_payment, residual_value, money_factor, lease_payment, doc_fee, other_fees, total_due, notes, created_at, updated_at, closed_at
`

type CreateDealParams struct {
	DealershipID             string         `json:"dealership_id"`
	CustomerID               string         `json:"customer_id"`
	VehicleID                uuid.NullUUID  `json:"vehicle_id"`
	SalespersonID            uuid.NullUUID  `json:"salesperson_id"`
	Status                   string         `json:"status"`
	DealType                 string         `json:"deal_type"`
	DeliveryMethod           string         `json:"delivery_method"`
	DeliveryDestinationState sql.NullString `json:"delivery_destination_state"`
	BillOfLading             sql.NullString `json:"bill_of_lading"`
	TaxStateCode             sql.NullString `json:"tax_state_code"`
	TaxJurisdictionCode      sql.NullString `json:"tax_jurisdiction_code"`
	TaxCombinedRate          sql.NullString `json:"tax_combined_rate"`
	TaxAmount                sql.NullString `json:"tax_amount"`
	SalePrice                sql.NullString `json:"sale_price"`
	TradeAllowance           sql.NullString `json:"trade_allowance"`
	TradePayoff              sql.NullString `json:"trade_payoff"`
	CashDown                 sql.NullString `json:"cash_down"`
	Rebates                  sql.NullString `json:"rebates"`
	AmountFinanced           sql.NullString `json:"amount_financed"`
	Apr                      sql.NullString `json:"apr"`
	TermMonths               sql.NullInt32  `json:"term_months"`
	MonthlyPayment           sql.NullString `json:"monthly_payment"`
	ResidualValue            sql.NullString `json:"residual_value"`
	MoneyFactor              sql.NullString `json:"money_factor"`
	LeasePayment             sql.NullString `json:"lease_payment"`
	DocFee                   sql.NullString `json:"doc_fee"`
	OtherFees                sql.NullString `json:"other_fees"`
	TotalDue                 sql.NullString `json:"total_due"`
	Notes                    sql.NullString `json:"notes"`
}

func (q *Queries) CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error) {
	row := q.db.QueryRowContext(ctx, createDeal,
		arg.DealershipID,
		arg.CustomerID,
		arg.VehicleID,
		arg.SalespersonID,
		arg.Status,
		arg.DealType,
		arg.DeliveryMethod,
		arg.DeliveryDestinationState,
		arg.BillOfLading,
		arg.TaxStateCode,
		arg.TaxJurisdictionCode,
		arg.TaxCombinedRate,
		arg.TaxAmount,
		arg.SalePrice,
		arg.TradeAllowance,
		arg.TradePayoff,
		arg.CashDown,
		arg.Rebates,
		arg.AmountFinanced,
		arg.Apr,
		arg.TermMonths,
		arg.MonthlyPayment,
		arg.ResidualValue,
		arg.MoneyFactor,
		arg.LeasePayment,
		arg.DocFee,
		arg.OtherFees,
		arg.TotalDue,
		arg.Notes,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.CustomerID,
		&i.VehicleID,
		&i.SalespersonID,
		&i.Status,
		&i.DealType,
		&i.DeliveryMethod,
		&i.DeliveryDestinationState,
		&i.BillOfLading,
		&i.TaxStateCode,
		&i.TaxJurisdictionCode,
		&i.TaxCombinedRate,
		&i.TaxAmount,
		&i.SalePrice,
		&i.TradeAllowance,
		&i.TradePayoff,
		&i.CashDown,
		&i.Rebates,
		&i.AmountFinanced,
		&i.Apr,
		&i.TermMonths,
		&i.MonthlyPayment,
		&i.ResidualValue,
		&i.MoneyFactor,
		&i.LeasePayment,
		&i.DocFee,
		&i.OtherFees,
		&i.TotalDue,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const deleteDeal = `-- name: DeleteDeal :exec
DELETE FROM deals
WHERE id = $1
`

func (q *Queries) DeleteDeal(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDeal, id)
	return err
}

const getDeal = `-- name: GetDeal :one
SELECT id, dealership_id, customer_id, vehicle_id, salesperson_id, status, deal_type, delivery_method, delivery_destination_state, bill_of_lading, tax_state_code, tax_jurisdiction_code, tax_combined_rate, tax_amount, sale_price, trade_allowance, trade_payoff, cash_down, rebates, amount_financed, apr, term_months, monthly_payment, residual_value, money_factor, lease_payment, doc_fee, other_fees, total_due, notes, created_at, updated_at, closed_at FROM deals
WHERE id = $1
`

func (q *Queries) GetDeal(ctx context.Context, id string) (Deal, error) {
	row := q.db.QueryRowContext(ctx, getDeal, id)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.CustomerID,
		&i.VehicleID,
		&i.SalespersonID,
		&i.Status,
		&i.DealType,
		&i.DeliveryMethod,
		&i.DeliveryDestinationState,
		&i.BillOfLading,
		&i.TaxStateCode,
		&i.TaxJurisdictionCode,
		&i.TaxCombinedRate,
		&i.TaxAmount,
		&i.SalePrice,
		&i.TradeAllowance,
		&i.TradePayoff,
		&i.CashDown,
		&i.Rebates,
		&i.AmountFinanced,
		&i.Apr,
		&i.TermMonths,
		&i.MonthlyPayment,
		&i.ResidualValue,
		&i.MoneyFactor,
		&i.LeasePayment,
		&i.DocFee,
		&i.OtherFees,
		&i.TotalDue,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listDeals = `-- name: ListDeals :many
SELECT id, dealership_id, customer_id, vehicle_id, salesperson_id, status, deal_type, delivery_method, delivery_destination_state, bill_of_lading, tax_state_code, tax_jurisdiction_code, tax_combined_rate, tax_amount, sale_price, trade_allowance, trade_payoff, cash_down, rebates, amount_financed, apr, term_months, monthly_payment, residual_value, money_factor, lease_payment, doc_fee, other_fees, total_due, notes, created_at, updated_at, closed_at FROM deals
ORDER BY created_at DESC
`

func (q *Queries) ListDeals(ctx context.Context) ([]Deal, error) {
	rows, err := q.db.QueryContext(ctx, listDeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.CustomerID,
			&i.VehicleID,
			&i.SalespersonID,
			&i.Status,
			&i.DealType,
			&i.DeliveryMethod,
			&i.DeliveryDestinationState,
			&i.BillOfLading,
			&i.TaxStateCode,
			&i.TaxJurisdictionCode,
			&i.TaxCombinedRate,
			&i.TaxAmount,
			&i.SalePrice,
			&i.TradeAllowance,
			&i.TradePayoff,
			&i.CashDown,
			&i.Rebates,
			&i.AmountFinanced,
			&i.Apr,
			&i.TermMonths,
			&i.MonthlyPayment,
			&i.ResidualValue,
			&i.MoneyFactor,
			&i.LeasePayment,
			&i.DocFee,
			&i.OtherFees,
			&i.TotalDue,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsByCustomer = `-- name: ListDealsByCustomer :many
SELECT id, dealership_id, customer_id, vehicle_id, salesperson_id, status, deal_type, delivery_method, delivery_destination_state, bill_of_lading, tax_state_code, tax_jurisdiction_code, tax_combined_rate, tax_amount, sale_price, trade_allowance, trade_payoff, cash_down, rebates, amount_financed, apr, term_months, monthly_payment, residual_value, money_factor, lease_payment, doc_fee, other_fees, total_due, notes, created_at, updated_at, closed_at FROM deals
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDealsByCustomer(ctx context.Context, customerID string) ([]Deal, error) {
	rows, err := q.db.QueryContext(ctx, listDealsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.CustomerID,
			&i.VehicleID,
			&i.SalespersonID,
			&i.Status,
			&i.DealType,
			&i.DeliveryMethod,
			&i.DeliveryDestinationState,
			&i.BillOfLading,
			&i.TaxStateCode,
			&i.TaxJurisdictionCode,
			&i.TaxCombinedRate,
			&i.TaxAmount,
			&i.SalePrice,
			&i.TradeAllowance,
			&i.TradePayoff,
			&i.CashDown,
			&i.Rebates,
			&i.AmountFinanced,
			&i.Apr,
			&i.TermMonths,
			&i.MonthlyPayment,
			&i.ResidualValue,
			&i.MoneyFactor,
			&i.LeasePayment,
			&i.DocFee,
			&i.OtherFees,
			&i.TotalDue,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsByDealership = `-- name: ListDealsByDealership :many
SELECT id, dealership_id, customer_id, vehicle_id, salesperson_id, status, deal_type, delivery_method, delivery_destination_state, bill_of_lading, tax_state_code, tax_jurisdiction_code, tax_combined_rate, tax_amount, sale_price, trade_allowance, trade_payoff, cash_down, rebates, amount_financed, apr, term_months, monthly_payment, residual_value, money_factor, lease_payment, doc_fee, other_fees, total_due, notes, created_at, updated_at, closed_at FROM deals
WHERE dealership_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDealsByDealership(ctx context.Context, dealershipID string) ([]Deal, error) {
	rows, err := q.db.QueryContext(ctx, listDealsByDealership, dealershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.CustomerID,
			&i.VehicleID,
			&i.SalespersonID,
			&i.Status,
			&i.DealType,
			&i.DeliveryMethod,
			&i.DeliveryDestinationState,
			&i.BillOfLading,
			&i.TaxStateCode,
			&i.TaxJurisdictionCode,
			&i.TaxCombinedRate,
			&i.TaxAmount,
			&i.SalePrice,
			&i.TradeAllowance,
			&i.TradePayoff,
			&i.CashDown,
			&i.Rebates,
			&i.AmountFinanced,
			&i.Apr,
			&i.TermMonths,
			&i.MonthlyPayment,
			&i.ResidualValue,
			&i.MoneyFactor,
			&i.LeasePayment,
			&i.DocFee,
			&i.OtherFees,
			&i.TotalDue,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsByStatus = `-- name: ListDealsByStatus :many
SELECT id, dealership_id, customer_id, vehicle_id, salesperson_id, status, deal_type, delivery_method, delivery_destination_state, bill_of_lading, tax_state_code, tax_jurisdiction_code, tax_combined_rate, tax_amount, sale_price, trade_allowance, trade_payoff, cash_down, rebates, amount_financed, apr, term_months, monthly_payment, residual_value, money_factor, lease_payment, doc_fee, other_fees, total_due, notes, created_at, updated_at, closed_at FROM deals
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDealsByStatus(ctx context.Context, status string) ([]Deal, error) {
	rows, err := q.db.QueryContext(ctx, listDealsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deal{}
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.CustomerID,
			&i.VehicleID,
			&i.SalespersonID,
			&i.Status,
			&i.DealType,
			&i.DeliveryMethod,
			&i.DeliveryDestinationState,
			&i.BillOfLading,
			&i.TaxStateCode,
			&i.TaxJurisdictionCode,
			&i.TaxCombinedRate,
			&i.TaxAmount,
			&i.SalePrice,
			&i.TradeAllowance,
			&i.TradePayoff,
			&i.CashDown,
			&i.Rebates,
			&i.AmountFinanced,
			&i.Apr,
			&i.TermMonths,
			&i.MonthlyPayment,
			&i.ResidualValue,
			&i.MoneyFactor,
			&i.LeasePayment,
			&i.DocFee,
			&i.OtherFees,
			&i.TotalDue,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeal = `-- name: UpdateDeal :one
UPDATE deals
SET
  dealership_id = COALESCE($2, dealership_id),
  customer_id = COALESCE($3, customer_id),
  vehicle_id = COALESCE($4, vehicle_id),
  salesperson_id = COALESCE($5, salesperson_id),
  status = COALESCE($6, status),
  deal_type = COALESCE($7, deal_type),
  delivery_method = COALESCE($8, delivery_method),
  delivery_destination_state = COALESCE($9, delivery_destination_state),
  bill_of_lading = COALESCE($10, bill_of_lading),
  tax_state_code = COALESCE($11, tax_state_code),
  tax_jurisdiction_code = COALESCE($12, tax_jurisdiction_code),
  tax_combined_rate = COALESCE($13, tax_combined_rate),
  tax_amount = COALESCE($14, tax_amount),
  sale_price = COALESCE($15, sale_price),
  trade_allowance = COALESCE($16, trade_allowance),
  trade_payoff = COALESCE($17, trade_payoff),
  cash_down = COALESCE($18, cash_down),
  rebates = COALESCE($19, rebates),
  amount_financed = COALESCE($20, amount_financed),
  apr = COALESCE($21, apr),
  term_months = COALESCE($22, term_months),
  monthly_payment = COALESCE($23, monthly_payment),
  residual_value = COALESCE($24, residual_value),
  money_factor = COALESCE($25, money_factor),
  lease_payment = COALESCE($26, lease_payment),
  doc_fee = COALESCE($27, doc_fee),
  other_fees = COALESCE($28, other_fees),
  total_due = COALESCE($29, total_due),
  notes = COALESCE($30, notes),
  updated_at = NOW()
WHERE id = $1
RETURNING id, dealership_id, customer_id, vehicle_id, salesperson_id, status, deal_type, delivery_method, delivery_destination_state, bill_of_lading, tax_state_code, tax_jurisdiction_code, tax_combined_rate, tax_amount, sale_price, trade_allowance, trade_payoff, cash_down, rebates, amount_financed, apr, term_months, monthly_payment, residual_value, money_factor, lease_payment, doc_fee, other_fees, total_due, notes, created_at, updated_at, closed_at
`

type UpdateDealParams struct {
	ID                       string         `json:"id"`
	DealershipID             string         `json:"dealership_id"`
	CustomerID               string         `json:"customer_id"`
	VehicleID                uuid.NullUUID  `json:"vehicle_id"`
	SalespersonID            uuid.NullUUID  `json:"salesperson_id"`
	Status                   string         `json:"status"`
	DealType                 string         `json:"deal_type"`
	DeliveryMethod           string         `json:"delivery_method"`
	DeliveryDestinationState sql.NullString `json:"delivery_destination_state"`
	BillOfLading             sql.NullString `json:"bill_of_lading"`
	TaxStateCode             sql.NullString `json:"tax_state_code"`
	TaxJurisdictionCode      sql.NullString `json:"tax_jurisdiction_code"`
	TaxCombinedRate          sql.NullString `json:"tax_combined_rate"`
	TaxAmount                sql.NullString `json:"tax_amount"`
	SalePrice                sql.NullString `json:"sale_price"`
	TradeAllowance           sql.NullString `json:"trade_allowance"`
	TradePayoff              sql.NullString `json:"trade_payoff"`
	CashDown                 sql.NullString `json:"cash_down"`
	Rebates                  sql.NullString `json:"rebates"`
	AmountFinanced           sql.NullString `json:"amount_financed"`
	Apr                      sql.NullString `json:"apr"`
	TermMonths               sql.NullInt32  `json:"term_months"`
	MonthlyPayment           sql.NullString `json:"monthly_payment"`
	ResidualValue            sql.NullString `json:"residual_value"`
	MoneyFactor              sql.NullString `json:"money_factor"`
	LeasePayment             sql.NullString `json:"lease_payment"`
	DocFee                   sql.NullString `json:"doc_fee"`
	OtherFees                sql.NullString `json:"other_fees"`
	TotalDue                 sql.NullString `json:"total_due"`
	Notes                    sql.NullString `json:"notes"`
}

func (q *Queries) UpdateDeal(ctx context.Context, arg UpdateDealParams) (Deal, error) {
	row := q.db.QueryRowContext(ctx, updateDeal,
		arg.ID,
		arg.DealershipID,
		arg.CustomerID,
		arg.VehicleID,
		arg.SalespersonID,
		arg.Status,
		arg.DealType,
		arg.DeliveryMethod,
		arg.DeliveryDestinationState,
		arg.BillOfLading,
		arg.TaxStateCode,
		arg.TaxJurisdictionCode,
		arg.TaxCombinedRate,
		arg.TaxAmount,
		arg.SalePrice,
		arg.TradeAllowance,
		arg.TradePayoff,
		arg.CashDown,
		arg.Rebates,
		arg.AmountFinanced,
		arg.Apr,
		arg.TermMonths,
		arg.MonthlyPayment,
		arg.ResidualValue,
		arg.MoneyFactor,
		arg.LeasePayment,
		arg.DocFee,
		arg.OtherFees,
		arg.TotalDue,
		arg.Notes,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.CustomerID,
		&i.VehicleID,
		&i.SalespersonID,
		&i.Status,
		&i.DealType,
		&i.DeliveryMethod,
		&i.DeliveryDestinationState,
		&i.BillOfLading,
		&i.TaxStateCode,
		&i.TaxJurisdictionCode,
		&i.TaxCombinedRate,
		&i.TaxAmount,
		&i.SalePrice,
		&i.TradeAllowance,
		&i.TradePayoff,
		&i.CashDown,
		&i.Rebates,
		&i.AmountFinanced,
		&i.Apr,
		&i.TermMonths,
		&i.MonthlyPayment,
		&i.ResidualValue,
		&i.MoneyFactor,
		&i.LeasePayment,
		&i.DocFee,
		&i.OtherFees,
		&i.TotalDue,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateDealStatus = `-- name: UpdateDealStatus :one
UPDATE deals
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, dealership_id, customer_id, vehicle_id, salesperson_id, status, deal_type, delivery_method, delivery_destination_state, bill_of_lading, tax_state_code, tax_jurisdiction_code, tax_combined_rate, tax_amount, sale_price, trade_allowance, trade_payoff, cash_down, rebates, amount_financed, apr, term_months, monthly_payment, residual_value, money_factor, lease_payment, doc_fee, other_fees, total_due, notes, created_at, updated_at, closed_at
`

type UpdateDealStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateDealStatus(ctx context.Context, arg UpdateDealStatusParams) (Deal, error) {
	row := q.db.QueryRowContext(ctx, updateDealStatus, arg.ID, arg.Status)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.CustomerID,
		&i.VehicleID,
		&i.SalespersonID,
		&i.Status,
		&i.DealType,
		&i.DeliveryMethod,
		&i.DeliveryDestinationState,
		&i.BillOfLading,
		&i.TaxStateCode,
		&i.TaxJurisdictionCode,
		&i.TaxCombinedRate,
		&i.TaxAmount,
		&i.SalePrice,
		&i.TradeAllowance,
		&i.TradePayoff,
		&i.CashDown,
		&i.Rebates,
		&i.AmountFinanced,
		&i.Apr,
		&i.TermMonths,
		&i.MonthlyPayment,
		&i.ResidualValue,
		&i.MoneyFactor,
		&i.LeasePayment,
		&i.DocFee,
		&i.OtherFees,
		&i.TotalDue,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}
