// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Deal struct {
	ID                       string         `json:"id"`
	DealershipID             string         `json:"dealership_id"`
	CustomerID               string         `json:"customer_id"`
	VehicleID                uuid.NullUUID  `json:"vehicle_id"`
	SalespersonID            uuid.NullUUID  `json:"salesperson_id"`
	Status                   string         `json:"status"`
	DealType                 string         `json:"deal_type"`
	DeliveryMethod           string         `json:"delivery_method"`
	DeliveryDestinationState sql.NullString `json:"delivery_destination_state"`
	BillOfLading             sql.NullString `json:"bill_of_lading"`
	TaxStateCode             sql.NullString `json:"tax_state_code"`
	TaxJurisdictionCode      sql.NullString `json:"tax_jurisdiction_code"`
	TaxCombinedRate          sql.NullString `json:"tax_combined_rate"`
	TaxAmount                sql.NullString `json:"tax_amount"`
	SalePrice                sql.NullString `json:"sale_price"`
	TradeAllowance           sql.NullString `json:"trade_allowance"`
	TradePayoff              sql.NullString `json:"trade_payoff"`
	CashDown                 sql.NullString `json:"cash_down"`
	Rebates                  sql.NullString `json:"rebates"`
	AmountFinanced           sql.NullString `json:"amount_financed"`
	Apr                      sql.NullString `json:"apr"`
	TermMonths               sql.NullInt32  `json:"term_months"`
	MonthlyPayment           sql.NullString `json:"monthly_payment"`
	ResidualValue            sql.NullString `json:"residual_value"`
	MoneyFactor              sql.NullString `json:"money_factor"`
	LeasePayment             sql.NullString `json:"lease_payment"`
	DocFee                   sql.NullString `json:"doc_fee"`
	OtherFees                sql.NullString `json:"other_fees"`
	TotalDue                 sql.NullString `json:"total_due"`
	Notes                    sql.NullString `json:"notes"`
	CreatedAt                time.Time      `json:"created_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
	ClosedAt                 sql.NullTime   `json:"closed_at"`
}
